# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

#BASE SETUP
title: Lost Boys
#email: jesse.n.peek@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tech and other ephemera 
url: "https://peeksake.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  peeksake
paginate: 5

show_downloads: false
google_analytics:
remote_theme: "dracula/gh-pages"
show_header: true

sass:
    style: compressed

#DRACULA THEME
#show_downloads: false
#google_analytics:
#remote_theme: "dracula/gh-pages"
#show_header: false
#
#sass:
#    style: compressed
#
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/